### ISSUE TITLE
breakpoints not being hit

### ISSUE THREAD

**Issue by Nathan187** [mpotthoff/vscode-android-webview-debug#6] opened 2022-01-24 01:25 UTC
has anyone had this issue?  

i set a breakpoint, however...it's not a solid red.  it says 'unbound breakpoint.'

has anyone seen this?  I've seen it before in other project but forgot how it was fixed

**Comment by mpotthoff** [comment] 2022-02-12 14:38
This is usually caused by the underlying vscode-js-debug extension not being able to match the remote file to your local file. This can be configured using the `pathMapping` and `sourceMapPathOverrides` options (See https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md). You can find more information using the diagnostic tool which can be started by typing `.scripts` into the debug console.

Because this is out of scope of this extension (which only does the connection setup between `vscode-js-debug` and the Android WebView) I'm going to close this issue.

**Closed as completed by mpotthoff** 2022-02-12 14:38 UTC
